"""
CareerMail AI — Notification Log model.

Stores history of sent, mock_sent, and failed notifications for auditing,
cooldown tracking, and UI display.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from sqlalchemy import DateTime, ForeignKey, Index, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class NotificationLog(Base):
    """Audit log of push notifications generated by CareerMail AI."""

    __tablename__ = "notification_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    opportunity_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("opportunities.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    notification_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )  # status_change, urgent_action, deadline, digest, test
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    data_payload: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="mock_sent",
        index=True,
    )  # sent, mock_sent, failed
    fcm_message_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    dedup_key: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )

    # Relationships
    user: Mapped["User"] = relationship("User", backref="notifications")
    opportunity: Mapped[Optional["Opportunity"]] = relationship("Opportunity", backref="notifications")

    __table_args__ = (
        Index("ix_notifications_user_type_created", "user_id", "notification_type", "created_at"),
        Index("ix_notifications_dedup", "user_id", "dedup_key", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<NotificationLog id={self.id} user_id={self.user_id} "
            f"type={self.notification_type!r} status={self.status!r}>"
        )
